---
title: "eds212-day4a"
format: html
editor_options: 
  chunk_output_type: console
---

33 Create Mattrices in R

```{r}
# create sequence of values ----
my_values <- seq(from =1, to = 10, by = 1)
my_values

# convert to matrix  ----
my_matrix <-matrix(my_values, 
                   nrow = 2,
                   ncol = 5,
                   byrow = TRUE)
class(my_matrix)

  
```
## Incorrectly declared matrix sizes
```{r}
matrix(my_values, nrow = 2,ncol = 3, byrow = TRUE)
```
## Let's do some math with matrices

```{r}
# scalar multiplication ----
4 * my_matrix

# Let's creat ea second matrix ----
my_values2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(data = my_values2, nrow = 2, byrow = TRUE)

# Add matrix----
my_matrix + my_matrix2

# stract matrix 
my_matrix - my_matrix2

```

```{r}
cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, byrow =TRUE)
dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)

cats %*% dogs 
```

# Leslie matrix example

```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), 
                       nrow = 3,
                       ncol = 3,
                       byrow = TRUE)

#initial starting conditions ----
insect_y0 <- c(12000, 700, 500)

# pop at year 1 ----
insect_y1 <- insect_leslie %*% insect_y0
insect_y1
```

# Find the number of individuals in the second year 

```{r}
insect_y2 <- insect_leslie %*% insect_y1
insect_y2

# Third year ----
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
```

```{r}
# Make the projection matrix ----
tree_rep <- matrix(c(0, 0, 50, 0.10, 0, 0, 0, 0.06, 0.95), nrow = 3, ncol = 3, byrow = TRUE)

# Check it out (it should look just like the one you drew!) ----
tree_rep
```

```{r}
# year 0: initial condition ----
tree_0 <- c(5000, 0, 0)

# year 1 ----
tree_1 <- tree_rep %*% tree_0
tree_1
```

```{r}
# year 2 ----
tree_2 <- tree_rep %*% tree_1
tree_2
```

```{r}
# year 3 ----
tree_3 <- tree_rep %*% tree_2
tree_3
```

```{r}
# year 4 ----
tree_4 <- tree_rep %*% tree_3
tree_4
```


